my homework lesson3
ssavl/learn_python pull request #2
Opened 2020-09-18 20:51 UTC by ssavl

my pull request

2020-09-19 09:14 UTC, technogleb requested changes
Добавить задание с датой и временем.
Необходимо исправить замечания.

2020-09-19 09:14 UTC, technogleb commented on lesson3/homework1.py
> +print(len(set(count_words.split())))
Почему используешь set()? В задании не было условия на уникальность.

2020-09-19 09:14 UTC, technogleb commented on lesson3/homework2.py
> +import csv
Где в задании этот модуль используется?

2020-09-19 09:14 UTC, technogleb commented on lesson3/homework2.py
> +    content = mycsv.write(str(lst).replace(',' ,':'))
Тебе необходимо было использовать модуль csv. А если точнее, csv.DictWriter

2020-09-19 11:59 UTC, ssavl commented on lesson3/homework1.py
> +print(len(set(count_words.split())))
Я гуглил с помощью какого метода это можно сделать, на stackoverflow нашел такое решение, но понял что тут сэт не нужен

2020-09-19 19:27 UTC, ssavl reviewed
my homework

2020-09-24 12:20 UTC, technogleb requested changes

2020-09-24 12:20 UTC, technogleb commented on lesson3/homework3.py
> +print(real_datetime)                # ЭТО УЖАСНЫЙ КОД, СОГЛАСЕН
Это не ужасный код, если не знать про существования функций datetime.strptime и strftime. Тебе необходимо использовать именно их, переделай пожалуйста.

2020-09-24 12:20 UTC, technogleb commented on lesson3/homework1.py
> +print(len(set(count_words.split())))
Переделай без Set

2020-09-24 12:20 UTC, technogleb commented on lesson3/homework2.py
> +import csv
по-прежнему не вижу использования модуля csv. 
Еще раз, тебе нужно использовать csv.DictWriter

2020-09-24 19:07 UTC, ssavl reviewed
убрал set ()

2020-09-24 19:07 UTC, ssavl commented on lesson3/homework2.py
> +    content = mycsv.write(str(lst).replace(',' ,':'))
Я понял, мне надо сделать новый пулу реквест с исправленным файлом? Кстати я сделал пул реквест в ветку Gleb_review дз с datetime буду благодарен за твой комментарии 🙏🏻

2020-09-24 19:10 UTC, technogleb requested changes
ДЗ с datetime просто исправляй, коммить, пуш и все. Новый пулл-реквест не нужен

2020-09-24 19:10 UTC, technogleb commented on lesson3/homework2.py
> +    content = mycsv.write(str(lst).replace(',' ,':'))
Не, не надо новый пулл реквест, просто исправляешь файл, коммитишь и заливаешь в ветку, он сам отобразится в пулл-реквесте

2020-09-24 19:53 UTC, ssavl reviewed
доделал конвертацию строки в формат класса datetime.datetime

2020-09-26 11:36 UTC, merged